name: Build Spigot and Create ZIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Asigură că tot istoricul Git este disponibil pentru rebase

    - name: Install Java and dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y -qq git openjdk-17-jdk maven zip

    - name: Run BuildTools
      run: |
        java -jar BuildTools.jar --rev 1.20.1

    - name: Create ZIP archive
      run: |
        mkdir -p dist
        zip -r -q dist/Spigot-1.20.1.zip . -x ".git/*" -x "dist/*" -x ".github/*" -x "BuildTools.jar"

    - name: Cleanup repository
      run: |
        find . -mindepth 1 -maxdepth 1 ! -name "dist" ! -name ".git" -exec rm -rf {} +

    - name: Force sync with remote and push ZIP archive
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/Spigot-1.20.1.zip
        git diff --quiet && git diff --staged --quiet || git commit -m "Added Spigot-1.20.1.zip"
        git fetch origin
        git reset --hard origin/main  # Sincronizează localul cu remote-ul
        git push --force
