name: Build Spigot and Create ZIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Java and dependencies
      run: |
        sudo apt update
        sudo apt install -y git openjdk-17-jdk maven zip

    - name: Download BuildTools.jar
      run: |
        curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

    - name: Run BuildTools
      run: |
        java -jar BuildTools.jar --rev 1.20.1

    - name: Create ZIP archive
      run: |
        mkdir -p dist
        zip -r dist/Spigot-1.20.1.zip . -x ".git/*" -x "dist/*"

    - name: Clean up unnecessary files
      run: |
        find . -mindepth 1 -maxdepth 1 ! -name 'dist' -exec rm -rf {} +

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and push ZIP archive
      run: |
        git add dist/Spigot-1.20.1.zip
        git commit -m "Added Spigot-1.20.1.zip"
        git push
      env:
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
